//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plotly {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plotly.Plotly.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;/&gt;
        ///    &lt;style&gt;
        ///        html, body, #root {
        ///            padding: 0;
        ///            margin: 0;
        ///            width: 100%;
        ///            height: 100%
        ///        }
        ///    &lt;/style&gt;
        ///    &lt;!--&lt;script src=&quot;https://cdn.plot.ly/plotly-latest.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;https://cdn.plot.ly/plotly-latest.min.js&quot;&gt;&lt;/script&gt;--&gt;
        ///    &lt;script src=&quot;plotly.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div id=&quot;root&quot;&gt;
        ///    &lt;div id=&quot;%ID%&quot; style=&quot;width: 100%; height: 100%;&quot;&gt;&lt;/div&gt;
        ///&lt;/div&gt;
        ///&lt;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Plotly_html {
            get {
                return ResourceManager.GetString("Plotly_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// The buffer module from node.js, for the browser.
        ///
        /// @author   Feross Aboukhadijeh &lt;feross@feross.org&gt; &lt;http://feross.org&gt;
        /// @license  MIT
        /// The buffer module from node.js, for the browser.
        ///
        /// @author   Feross Aboukhadijeh &lt;https://feross.org&gt;
        /// @license  MIT
        /// @overview es6-promise - a tiny implementation of Promises/A+.
        /// @copyright Copyright (c) 2014 Yehuda Katz, Tom Dale, Stefan Penner and contributors (Conversion to ES6 API by Jake Archibald)
        /// @license   Licensed under MIT license
        ///            See https://r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string plotly_js {
            get {
                return ResourceManager.GetString("plotly_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
        ///$jscomp.defineProperty=$jscomp.ASSUME_ES5||&quot;function&quot;==typeof Object.defineProperties?Obje [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlotlyApp_js {
            get {
                return ResourceManager.GetString("PlotlyApp_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PlotlyWorker_js {
            get {
                return ResourceManager.GetString("PlotlyWorker_js", resourceCulture);
            }
        }
    }
}
